apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: roombasedsoundboard
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: |
	backend=ghcr.io/youllou/roombased_soundboard-backend:latest
        frontend=ghcr.io/youllou/roombased_soundboard-frontend:latest
    argocd-image-updater.argoproj.io/backend.update-strategy: digest
    argocd-image-updater.argoproj.io/frontend.update-strategy: digest
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: rmbsndb
  source:
    repoURL: git@github.com:Youllou/k8s-youllou.com.git
    targetRevision: main
    path: apps/roombasedsoundboard/prod
  syncPolicy:
    syncOptions:
      - CreateNamespace=true
    automated:
      selfHeal: true
      prune: true
