global:
  domain: argocd.youllou.com

server:
  insecure: true
  ingress:
    enabled: false

  extraArgs:
    - --insecure

  service:
    type: ClusterIP

  config:
    admin.enabled: true
    url: https://argocd.youllou.com

configs:
  cm:
    create: true
    url: https://argocd.youllou.com
    kustomize.buildOptions: --enable-helm

statusbadge.enabled: false

## edit secret kubectl edit secret argocd-authentik-secret -n argocd to add annotation app.kubernetes.io/part-of: argocd

dex:
  enabled: false
  config: |
    connectors:
      - type: oidc
        id: authentik
        name: authentik
        config:
          issuer: https://auth.jg1g.com/application/o/argocd/
          clientID: diJFLxnLM97PbzBc80DIdFUtRQUck2gF5uv6eTbs
          clientSecret: $argocd-authentik-secret:dex.authentik.clientSecret
          insecureEnableGroups: true
          scopes:
            - openid
            - profile
            - email

controller:
  metrics:
    enabled: true

repoServer:
  metrics:
    enabled: true

applicationSet:
  metrics:
    enabled: true
