apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-statefulset
  namespace: swinceomatik
spec:
  serviceName: mysql-scv
  replicas: 1
  selector:
    matchLabels:
      app: mysql-statefulset
  template:
    metadata:
      labels:
        app: mysql-statefulset
    spec:
      containers:
        - name: mysql
          image: mysql:8.2
          env:
            - name: MYSQL_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: swinceomatik-secrets
                  key: MYSQL_ROOT_PASSWORD
          ports:
            - containerPort: 3306
          volumeMounts:
            - name: mysql-pvc
              mountPath: /var/lib/mysql
            - name: mysql-init
              mountPath: /docker-entrypoint-initdb.d
      volumes:
        - name: mysql-pvc
          persistentVolumeClaim:
            claimName: mysql-pvc
        - name: mysql-init
          configMap:
            name: mysql-configmap
