apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  namespace: swinceomatik
spec:
  selector:
    app: mysql-svc
  ports:
    - port: 3306
      targetPort: 3306
  clusterIP: None   # headless, standard for StatefulSets
