apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: storage
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  source:
    repoURL: git@github.com:Youllou/k8s-youllou.com.git
    targetRevision: main
    path: storage
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
