apiVersion: apps/v1
kind: Deployment
metadata:
  name: youllou
  annotations:
    kube-score/ignore: pod-networkpolicy,container-image-tag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: youllou
  template:
    metadata:
      labels:
        app: youllou
    spec:
      imagePullSecrets:
        - name: ghcr-deploy-token
      containers:
        - name: youllou
          image: ghcr.io/youllou/youllou.com:latest
          imagePullPolicy: Always
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 10
          ports:
            - containerPort: 3000
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsNonRoot: true
            runAsUser: 10001
            runAsGroup: 10001
            capabilities:
              drop:
                - ALL
            seccompProfile:
              type: RuntimeDefault
