apiVersion: apps/v1
kind: Deployment
metadata:
  name: rmbsndb-minio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rmbsndb-minio
  template:
    metadata:
      labels:
        app: rmbsndb-minio
    spec:
      containers:
        - name: minio
          image: minio/minio:latest
          args: ["server", "/data", "--console-address", ":9001"]
          envFrom:
            - secretRef:
                name: rmbsndb-secrets
          ports:
            - containerPort: 9000
            - containerPort: 9001
          volumeMounts:
            - name: data
              mountPath: /data
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 512Mi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: rmbsndb-minio-data
