apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - resources/ingress.yaml

configMapGenerator:
  - name: argocd-cm
    namespace: argocd
    behavior: merge
    literals:
      - accounts.website_user=apiKey, login
      - accounts.alice.enabled=true

helmCharts:
- name: argo-cd
  repo: oci://ghcr.io/argoproj/argo-helm
  version: 10.1.2
  releaseName: argocd
  apiVersions:
  - monitoring.coreos.com/v1
  valuesFile: helm/values.yaml
