apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: argocd

resources:
  - resources/

patches:
  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-cm
        namespace: argocd
      data:
        accounts.website_user: apiKey

  - patch: |-
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: argocd-rbac-cm
        namespace: argocd
      data:
        policy.csv: |
          p, website_user, applications, get, my-project/*, allow
          g, embed-user, role:readonly-embed
helmCharts:
- name: argo-cd
  repo: oci://ghcr.io/argoproj/argo-helm
  version: 10.1.2
  releaseName: argocd
  apiVersions:
  - monitoring.coreos.com/v1
  valuesFile: helm/values.yaml
